### ISSUE TITLE
Javascript setting a cookie client-side is not propagated to victim

### ISSUE THREAD

**Issue by ZetaTwo** [mandatoryprogrammer/CursedChrome#17]
If a cookie is set in a javascript this will not be properly propagated back to the victim and used in requests. One potential way this could be fixed is to run some kind of helper/extension on the attacker side which could send some kind of control messages to the proxy to set these cookies on the victim side as well.

PS. Sorry for dropping a batch of issues like this. We have an ambition of providing PRs as well but letting you know about these things straight away in the meantime.

**Comment by mmangione** [comment]
+1 on this as well. For our use case, which is actually not even Red Team, we simply need to capture the cookies from the user’s browser and store the state so we can resume where we left off.

I think it might be best to address this with a cookies entry in the PostgreSQL DB. The JSON field would be able to hold all manner of dynamic cookies and we could keep state between sessions.

**Comment by mandatoryprogrammer** [comment]
Because I love all of you (and had this same issue bite me recently). This functionality was added in PR #22, which adds support for syncing victim's cookies to your own browser via a custom Firefox/Chrome extension if your remote implant has the `cookies` permission.

See the updated README for more info, let me know if this doesn't address any of the edge cases you were experiencing!
