### ISSUE TITLE
Cookies already present on the victim not propagated to attacker

### ISSUE THREAD

**Issue by ZetaTwo** [mandatoryprogrammer/CursedChrome#18]
In some cases, cookie values are used inside javascript code to calculate for example CSRF headers. If this cookie is already set on the client when the attack begins. It would be good if there was a way to "sync" previously set cookies back to the attacker to make sure the state is as similar as possible between the two browsers.

PS. Sorry for dropping a batch of issues like this. We have an ambition of providing PRs as well but letting you know about these things straight away in the meantime.

**Comment by mmangione** [comment]
Yeah. I was just thinking about this problem as well. +1 it needs to be addressed

**Comment by mandatoryprogrammer** [comment]
Thanks for the submission, this is a big TODO feature-wise (probably the most important one IMO). I'll try to work on this soon.

**Comment by mandatoryprogrammer** [comment]
Because I love all of you (and had this same issue bite me recently). This functionality was added in PR #22, which adds support for syncing victim's cookies to your own browser via a custom Firefox/Chrome extension if your remote implant has the `cookies` permission.

See the updated README for more info, let me know if this doesn't address any of the edge cases you were experiencing!
